name: poke_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

    - assets/images/

    - assets/images/sprites_pokemons/

    - assets/images/images_pokemons/

    - assets/images/trainers/
    - assets/images/trainers/back/
    - assets/images/trainers/class/

    - assets/images/attacks_icons/

    - assets/images/types/
    - assets/images/types/bug/
    - assets/images/types/bug/back/
    - assets/images/types/bug/icon/colorful/
    - assets/images/types/bug/icon/white/
    - assets/images/types/dark/back/
    - assets/images/types/dark/icon/colorful/
    - assets/images/types/dark/icon/white/
    - assets/images/types/dragon/back/
    - assets/images/types/dragon/icon/colorful/
    - assets/images/types/dragon/icon/white/
    - assets/images/types/electric/back/
    - assets/images/types/electric/icon/colorful/
    - assets/images/types/electric/icon/white/
    - assets/images/types/fairy/icon/colorful/
    - assets/images/types/fighting/back/
    - assets/images/types/fighting/icon/colorful/
    - assets/images/types/fighting/icon/white/
    - assets/images/types/fire/back/
    - assets/images/types/fire/icon/colorful/
    - assets/images/types/fire/icon/white/
    - assets/images/types/flying/back/
    - assets/images/types/flying/icon/colorful/
    - assets/images/types/flying/icon/white/
    - assets/images/types/ghost/back/
    - assets/images/types/ghost/icon/colorful/
    - assets/images/types/ghost/icon/white/
    - assets/images/types/grass/back/
    - assets/images/types/grass/icon/colorful/
    - assets/images/types/grass/icon/white/
    - assets/images/types/ground/back/
    - assets/images/types/ground/icon/colorful/
    - assets/images/types/ground/icon/white/
    - assets/images/types/ice/back/
    - assets/images/types/ice/icon/colorful/
    - assets/images/types/ice/icon/white/
    - assets/images/types/normal/back/
    - assets/images/types/normal/icon/colorful/
    - assets/images/types/normal/icon/white/
    - assets/images/types/poison/back/
    - assets/images/types/poison/icon/colorful/
    - assets/images/types/poison/icon/white/
    - assets/images/types/psychic/back/
    - assets/images/types/psychic/icon/colorful/
    - assets/images/types/psychic/icon/white/
    - assets/images/types/rock/back/
    - assets/images/types/rock/icon/colorful/
    - assets/images/types/rock/icon/white/
    - assets/images/types/steel/back/
    - assets/images/types/steel/icon/colorful/
    - assets/images/types/steel/icon/white/
    - assets/images/types/water/back/
    - assets/images/types/water/icon/colorful/
    - assets/images/types/water/icon/white/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
